FROM apache/spark:v3.1.3 as spark

FROM apache/zeppelin:0.10.0

COPY --from=spark /opt/spark /opt/spark

USER root

RUN wget https://repo1.maven.org/maven2/org/postgresql/postgresql/42.2.5/postgresql-42.2.5.jar && \
    mv postgresql-42.2.5.jar /opt/spark/jars/


ENV SPARK_HOME /opt/spark
